<a href="https://colab.research.google.com/github/manojDOX/ML_TensorFlow/blob/main/TFFE_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
def p_value (n,a):
  print("printing for- "+a)
  print("the value defined was- "+str(n.numpy()))

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [ ]:
a='scaler'
A=tf.constant(1)
p_value(A,a)
b='matrix'
B=tf.constant([[1,2],[3,4]])
p_value(B,b)
c='vector'
C=tf.constant([1,2,3,4])
p_value(C,c)
d='tensor'
D=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
p_value(D,d)

printing for- scaler
the value defined was- 1
printing for- matrix
the value defined was- [[1 2]
 [3 4]]
printing for- vector
the value defined was- [1 2 3 4]
printing for- tensor
the value defined was- [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2. Find the shape, rank and size of the tensors you created in 1.

In [ ]:
sh='shape '
ra=' rank '
si=' size '
print(sh+str(A.shape) + ra + str(A.ndim) + si + str(tf.size(A).numpy()))
print(sh+str(B.shape) + ra + str(B.ndim) + si + str(tf.size(B).numpy()))
print(sh+str(C.shape) + ra + str(C.ndim) + si + str(tf.size(C).numpy()))
print(sh+str(D.shape) + ra + str(D.ndim) + si + str(tf.size(D).numpy()))

shape () rank 0 size 1
shape (2, 2) rank 2 size 4
shape (4,) rank 1 size 4
shape (2, 2, 2) rank 3 size 8


3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
tf.random.set_seed(42)
v_a=tf.random.uniform(shape=[5,300],minval=0,maxval=1)
v_b=tf.random.uniform(shape=[5,300],minval=0,maxval=1)
v_a[0,0],v_b[0,0]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.6645621>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.68789124>)

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
v_c=tf.matmul(tf.transpose(v_a),v_b)

5. Multiply the two tensors you created in 3 using dot product.

In [ ]:
v_d=v_a*v_b

In [ ]:
v_c.numpy(),v_d.numpy()

(array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
         1.6227092 ],
        [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
         1.1739546 ],
        [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
         1.481925  ],
        ...,
        [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
         1.5979093 ],
        [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
         1.924531  ],
        [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
         1.0476992 ]], dtype=float32),
 array([[4.57146466e-01, 2.13658452e-01, 3.28531623e-01, ...,
         2.17384368e-01, 2.51955122e-01, 3.40777524e-02],
        [1.45614594e-01, 3.09705492e-02, 6.57417625e-02, ...,
         2.36865208e-01, 9.56212804e-02, 1.13281950e-01],
        [7.73395528e-04, 1.34753399e-02, 7.99194753e-01, ...,
         1.22185037e-01, 4.81487900e-01, 7.18945917e-03],
        [6.55430436e-01, 5.7697963

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
v_e=tf.random.uniform(shape=[224,224,3],minval=0,maxval=1)

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [ ]:
min_values = tf.reduce_min(v_e, axis=0)
max_values = tf.reduce_max(v_e, axis=0)

In [ ]:
min_values[0:10],max_values[0:10]

(<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
 array([[0.00267446, 0.00214839, 0.00105965],
        [0.00547564, 0.00221121, 0.00415409],
        [0.00372386, 0.00520217, 0.00090277],
        [0.00111604, 0.00635767, 0.00318384],
        [0.00210273, 0.00058484, 0.00105011],
        [0.00426018, 0.01587307, 0.00121641],
        [0.00651884, 0.00117064, 0.00271463],
        [0.00567365, 0.00854075, 0.01529098],
        [0.00719798, 0.00084388, 0.00191796],
        [0.00047123, 0.00639832, 0.00217664]], dtype=float32)>,
 <tf.Tensor: shape=(10, 3), dtype=float32, numpy=
 array([[0.99845374, 0.99930906, 0.99262166],
        [0.99466574, 0.99434555, 0.9957906 ],
        [0.9993377 , 0.9988344 , 0.99788725],
        [0.9930023 , 0.99388456, 0.9973532 ],
        [0.99890304, 0.99934196, 0.999063  ],
        [0.99909663, 0.9912498 , 0.9989666 ],
        [0.9984517 , 0.9993125 , 0.9972266 ],
        [0.9851161 , 0.9997518 , 0.9938358 ],
        [0.99558496, 0.9875896 , 0.99800336],
        

8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [58]:
sq_value=tf.random.uniform(shape=[1,224,224,3])
sq_value.shape

TensorShape([1, 224, 224, 3])

In [59]:
tf.squeeze(sq_value).shape

TensorShape([224, 224, 3])

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [66]:
o_h_value=tf.random.uniform(shape=[10],minval=0,maxval=10,dtype=tf.int32)
o_h_value

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([6, 7, 4, 8, 0, 2, 2, 5, 8, 5], dtype=int32)>

10. One-hot encode the tensor you created in 9.

In [72]:
tf.one_hot(o_h_value,depth=10).numpy()

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]], dtype=float32)